### ISSUE TITLE
Connection defined with env variables doesn't appear in connection_list with docker.

### ISSUE THREAD

**Issue by desprit** [mrvautin/adminMongo#121]
I tried to run adminmongo docker container like this:
```
docker run 
  -d 
  -e "CONN_NAME=localhost" 
  -e "DB_USERNAME=root" 
  -e "DB_PASSWORD=root" 
  -e "DB_HOST=127.0.0.1"
  --network host 
  adminmongo
```

and from docker-compose:
```
version: '2.0'
services:
  adminmongo:
    image: adminmongo
    network_mode: "host"
    environment:
     - CONN_NAME=localhost
     - DB_USERNAME=root
     - DB_PASSWORD=root
     - DB_HOST=127.0.0.1
```

Docker container starts and I'm able to open web interface. But connections section remains empty and I have to add new connection every time I restart adminmongo service.
Is it a bug or did I just miss something?
