### ISSUE TITLE
Can't run adminMongo with docker-compose

### ISSUE THREAD

**Issue by serge1peshcoff** [mrvautin/adminMongo#136]
I use `docker-compose` to run multi-container environment. But I can't integrate adminMongo into it.
Here is my docker-compose.yml:

```
version: '2'

services:

    // other services
    adminmongo:
        build: ./adminmongo
        ports:
            - "1234:1234"
        links:
            - mongodb
        volumes:
            - "./adminmongo/app.js:/config/app.js:ro"
```

`adminmongo/Dockerfile`:

```
FROM mrvautin/adminmongo

EXPOSE 1234
```

`adminmongo/app.js`

```
module.exports = {
    "app": {
        "host": "localhost",
        "port": 1234,
        "locale": "en",
        "context": "dbApp",
        "monitoring": true
    }
}
```

When I run `docker-compose up`, the only output from this container I'm getting is:

`docker_adminmongo_1 exited with code 0`

If I rename `app.js` to `app.json` and change the filename in `docker-compose.yml`, here is what I'm getting:
```

adminmongo_1          | module.js:472
adminmongo_1          |     throw err;
adminmongo_1          |     ^
adminmongo_1          | 
adminmongo_1          | Error: Cannot find module '/config/app.js'
adminmongo_1          |     at Function.Module._resolveFilename (module.js:470:15)
adminmongo_1          |     at Function.Module._load (module.js:418:25)
adminmongo_1          |     at Module.runMain (module.js:605:10)
adminmongo_1          |     at run (bootstrap_node.js:420:7)
adminmongo_1          |     at startup (bootstrap_node.js:139:9)
adminmongo_1          |     at bootstrap_node.js:535:3
...
docker_adminmongo_1 exited with code 1
```

I'm not sure if it's the docker issue or I set up something wrong, can you please help me figuring this out?

**Comment by mrvautin** [comment]
I'm not familiar with Docker. Hopefully someone else can assist here?

**Comment by ianfinch** [comment]
Instead of volume-mapping in config/app.js, why don't you just use environmental variables to override the values you wish to change?

E.g. I am using the CONTEXT environment variable to move my base URL to /mongo.

I'm doing it in Kubernetes rather than docker-compose, but the principle should be the same.

**Comment by dianjuar** [comment]
I used this image https://store.docker.com/community/images/adicom/admin-mongo works pretty fine

My docker-compose service is 

```yaml
  adminmongo:
    image: mrvautin/adminmongo
    restart: "always"
    environment:
      - CONN_NAME=whatever
      - DB_HOST=mongodb
      - DB_PORT=27017
    ports:
      - "1234:1234"
    links:
      - mongodb
```

The image has this environmental variables to configure adminMongo

Env variable name | Description
-- | --
CONN_NAME | The name of the connection to create on boot
DB_USERNAME | The username for the database connection
DB_PASSWORD | The password fot the database user
DB_HOST | The host IP address or DNS name without the port!
DB_PORT | The port of the mongoDB database, if not provided the default 27017 will be used

**Comment by elussich** [comment]
Hello there!

@serge1peshcoff, I've used that last piece of info from @dianjuar (thanks Diego!) and managed to compose MongoDB and adminMongo together successfully.

This is a simplified version of my `docker-compose.yml` file:
```yaml
version: '2'
services:
  mongo-service:
    image: mongo
    ports: ['27017:27017']
  adminmongo-service:
    image: mrvautin/adminmongo
    links: ['mongo-service:mongo']
    environment:
      CONN_NAME: 'whatever'
      # note this host name is the one we specified as an alias, when linking to the `mongo-service`
      DB_HOST: 'mongo'
    ports: ['1234:1234']
```

Hope this shed some more light into the original issue.
Cheers!

**Comment by gajupo** [comment]
Hello there!
I am having issues trying getting running adminMongo + mongo docker image. After execute docker-compose, services are running but I am not able to reach adminMongo site through http://localhost:1234

```yml
version: '3'
services:
   mongodb_service:
     image: mongo
     environment:
       - MONGO_INITDB_DATABASE=strapi
     ports:
       - 27017:27017
     volumes:
       - ./db:/data/db
     restart: always
   adminmongo:
     image: mrvautin/adminmongo
     restart: always
     environment:
       - CONN_NAME=mongo_conn
       - DB_HOST=mongodb_service
       - DB_PORT=27017
     ports:
       - 1234:1234
     links:
       - mongodb_service
```
Can any body give some glue what I am doing wrong?

**Comment by ashnehete** [comment]
@gajupo I was facing the same issue and adding `HOST=0.0.0.0` to the environment variables solved it for me.

So your `docker-compose.yml` will look like,
```yaml
version: '3'
services:
   mongodb_service:
     image: mongo
     environment:
       - MONGO_INITDB_DATABASE=strapi
     ports:
       - 27017:27017
     volumes:
       - ./db:/data/db
     restart: always
   adminmongo:
     image: mrvautin/adminmongo
     restart: always
     environment:
       - CONN_NAME=mongo_conn
       - DB_HOST=mongodb_service
       - DB_PORT=27017
       - HOST=0.0.0.0
     ports:
       - 1234:1234
     links:
       - mongodb_service
```

For any server to be accessible from outside the docker world, the server needs to be published at `0.0.0.0` but the default configuration publishes it at `localhost`.
