### ISSUE TITLE
How do I connect if the password contains an @ sign?

### ISSUE THREAD

**Issue by Gilwyad** [mrvautin/adminMongo#147]
I get:

Config error: Error: Username containing an unescaped at-sign

How do I escape it? Should it work if I change it to %40?

**Comment by mrvautin** [comment]
Yes it should work. Try here: http://stackoverflow.com/questions/7486623/mongodb-password-with-in-it

**Comment by Dawensky** [comment]
Config error: Error: Username containing an unescaped at-sign

what exactly is does this means? I have replaced the **@** sign in the password to **!** but still getting the error message. So what exactly is it saying?

Please help

**Comment by GauzStudio** [comment]
I have the same problem.

Even with: p%40ssword@username
I still get: Error: Username containing an unescaped at-sign

**Comment by tadams10** [comment]
I also have this issue with the %40

**Comment by shadya786** [comment]
i have also same issue Even with: p%40ssword@username
I still get: Error: Username containing an unescaped at-sign

**Comment by dsingh09** [comment]
Simply Use "mongodb://username:"+encodeURIComponent("p@ssword")+"@localhost:27017/droom"

**Comment by dsingh09** [comment]
Simply Use "mongodb://username:"+encodeURIComponent("p@ssword")+"@localhost:27017/database"

**Comment by bolorundurovj** [comment]
Just change the password

**Comment by vocchiogrosso** [comment]
Replace the @ with %40 and it will work :)

**Comment by Snedden** [comment]
nothing seems to work for , seesms like my app decodes the @ sign somewhere before passing it to cluster authentication on remote server, 

It sucks but I had to change my password

**Comment by harish-everest** [comment]
Hope it helps
https://stackoverflow.com/questions/7486623/mongodb-password-with-in-it

**Comment by thavamm** [comment]
I had same issue with my docker-compose.yml for prisma. I replaced "@" with "%40" then it works fine. 

```
 myprisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: "mongodb://test:test%40333@mongo"
```
