### ISSUE TITLE
Environment variables are not used at all

### ISSUE THREAD

**Issue by necramirez** [mrvautin/adminMongo#166]
Apparently, if `config/app.json` already exists, the app ignores all env vars.

This is my `Dockerfile` that works:
```diff
  FROM node:latest

  COPY . /app/user

  WORKDIR /app/user
  RUN npm install
+ RUN chmod -R 775 .
+ RUN rm config/app.json
  CMD node app.js
```

Question:  Is this the desired behavior?  Or should we allow both config sources to co-exist?  I prefer the latter, such that env vars may override whatever's in the config file.

**Comment by blurrcat** [comment]
I wasted an afternoon debugging this. Thanks @necramirez!
Other people, another workaround for now is `docker run -e PASSWORD=password4u mrvauntin/adminmongo /bin/sh -c "rm config/app.json; node app.js"`.

**Comment by geekscrapy** [comment]
I can confirm this issue as well, also when I tried @blurrcat solution, it doesn't change anything...

**Comment by PaulMonnery** [comment]
Old issue but it's still a problem
I found a (terrible) workaround to fix auto connection
```
  mongo-admin:
    image: mrvautin/adminmongo:latest
    ports:
      - "1234:1234"
    environment:
      - CONFIG={"connections":{"dashboard":{"connection_string":"mongodb://db/react_passport","connection_options":{}}}}
      - APP={"app":{"host":"0.0.0.0"}}
      - HOST=0.0.0.0
    command: "/bin/sh -c 'echo $$CONFIG > config/config.json ; echo $$APP > config/app.json ; node app.js'"
    restart: always
    depends_on:
      - db
    networks:
      dashboard:
```
I put the JSON that will be parsed for connections directly inside the environment. The `$$` escapes the value of the variable, see this [stackoverflow post](https://stackoverflow.com/questions/40447029/docker-compose-environment-variable-for-command)

**Comment by SalahAdDin** [comment]
@PaulMonnery It is not required, 
if you pass a folder with both `app.json` and `config.json` to the container, it will work:
```yaml
access_database:
    container_name: access_mongo_db
    image: mrvautin/adminmongo
    restart: always
    environment:
      - HOST=0.0.0.0
    ports:
      - 1234:1234
    links:
      - database
    volumes: 
      - ./mongo/admin/:/app/user/config/:ro
```
