### ISSUE TITLE
Environment Variable CONTEXT does not work.

### ISSUE THREAD

**Issue by offbeatful** [mrvautin/adminMongo#201]
I use the following docker-compose file:

```yaml
  mongo-ui:
    container_name: mongo-ui
    image: mrvautin/adminmongo:latest   
    restart: always    
    user: root
    ports:      
      - 80:80
    environment:      
      - PORT=80
      - CONTEXT=mongo
      - CONN_NAME=default
      - DB_HOST=db
```

When composed I try to access admin-mongo at http://localhost/mongo and get 404.

Logs:
`
Error: Not Found
    at /app/user/app.js:226:15
    at Layer.handle [as handle_request] (/app/user/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/user/node_modules/express/lib/router/index.js:317:13)
    at /app/user/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/user/node_modules/express/lib/router/index.js:335:12)
    at next (/app/user/node_modules/express/lib/router/index.js:275:10)
    at /app/user/node_modules/express/lib/router/index.js:635:15
    at next (/app/user/node_modules/express/lib/router/index.js:260:14)
    at next (/app/user/node_modules/express/lib/router/route.js:127:14)
    at /app/user/routes/index.js:8:5
GET /mongo 404 88.565 ms - 8911
`

I tried setting context to /mongo as well - same result.

Please advice.
