### ISSUE TITLE
Issue with docker-compose

### ISSUE THREAD

**Issue by thomasd3** [mrvautin/adminMongo#224]
I am trying to get adminMongo to connect to the mongo instance from the same docker compose.
that instance is not visible from the outside, so entering the ip/port for the connection in the UI doesn't make any sense.

I tried to add:
```
     environment:
       CONN_NAME: test
       DB_HOST: mongodb. // name of the mongo container
       DB_PORT: 27017

```
but it doesn't do anything.

Is there a solution for this?
