### ISSUE TITLE
Need an env var to supply connectionString

### ISSUE THREAD

**Issue by troykelly** [mrvautin/adminMongo#266]
Need to be able to provide the `connectionString` rather than host and port for docker containers.

**Comment by andrewwippler** [comment]
I think you may be confused what this does. `adminMongo` connects to a server and not to a particular database via `connectionString`. 

An example with `docker-compose`:

```
version: '3'
services:
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "1234:1234"
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
```
