### ISSUE TITLE
connection settings in docker container are not working

### ISSUE THREAD

**Issue by flashpixx** [mrvautin/adminMongo#279]
I'm using in my docker-compose th following configuration for admin mongo:

```
  adminmongo:
    image: mrvautin/adminmongo:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - ${EXPOSE_PORT_MONGOADMIN:-1234}:1234
    environment:
      - HOST=adminmongo
      - CONN_NAME=mydb
      - DB_HOST=mongodb
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - ${EXPOSE_PORT_GRAPHEXPLORER:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - ./mongodb/00-schema.js:/docker-entrypoint-initdb.d/00-schema.js
```

in general connection to the MongoDB database instance are quite working, but I need to setup the connection settings manually on the UI, so the environment variables on the container are not working
